### ISSUE TITLE
Unparsable manifest 

### ISSUE THREAD

**Issue by leoek** [klemens/2i-emulator#3]
Thats the error i get trying to compile with `cargo build --release`
I get the same error if i checkout v2.0.0
```
Unable to update https://github.com/klemens/rustyline.git?branch=2i-emulator#291927c2

Caused by:
  failed to parse manifest at `.cargo/git/checkouts/rustyline-1baacae604cf1983/2i-emulator/Cargo.toml`

Caused by:
  could not parse input as TOML
/home/leo/.cargo/git/checkouts/rustyline-1baacae604cf1983/2i-emulator/Cargo.toml:19:9 expected a key but found an empty string
/home/leo/.cargo/git/checkouts/rustyline-1baacae604cf1983/2i-emulator/Cargo.toml:19:9-19:10 expected `.`, but found `'`
```

**Comment by klemens** [comment]
This is caused by the cargo version being to old. I guess you are using ubuntu LTS or similar which e.g. only provides rust 1.7.0 and cargo 0.8.0. The emulator needs at least rust 1.13.0 and cargo 0.9.0. I suggest [installing a recent rust](https://www.rust-lang.org/en-US/install.html).

If you just want to use the emulator, I also provide [compiled versions](https://github.com/klemens/2i-emulator/releases) for windows and linux for every release, that should work out of the box.

**Comment by leoek** [comment]
Thank you! That solved it. Maybe you could add these information to the Readme. Debian has old versions too (as expected.. should have thought of that).

About the compiled versions: I downloaded the 2i-emulator-2.0.0-linux-x86_64.tar.xz, and tried to execute the 2i-emulator, but got an "Exec format error".

**Comment by klemens** [comment]
Hm, do you maybe run an x86 (32 bit) OS instead of an x86_64 one? What does `uname -a` print for you?

**Comment by leoek** [comment]
Yep, I do. Building it myself for i686 worked fine tho.

**Comment by klemens** [comment]
I added a i686 binary to the release for those who do not want to build it themselves.

**Comment by klemens** [comment]
I now also added a comment to the README like you suggested. It turns out you need at least 1.15.0. 😅

**Comment by leoek** [comment]
:+1: I am not sure if there is any distro which has such a new rustc version.. maybe arch :) Thanks again for the quick help and the improvement of the readme!
